name: Binance Square Bot

on:
  workflow_dispatch:

  jobs:
    test:
        runs-oSQUARE_OPENAPI_K_OPENAPI_KEBINANCE_SQUARE_OPENAPI_KEBINANCE_SQUARE_OPENAPI_KEY }}

            stepses: acti- uses: actionv4
                n: node bot/index.mjsode-version: 24

                      - run: node bot/index.mjsode-version: 24

                            - run: node bot/index.mjs
