name: Binance Squst:
    runs-on: ubuntE_OPENAPI_    BINANCE_SQUARE_OPENAPI_    BINANCE_SQUARE_OPENAPI_KEY: ${{ secrets.BINANCE_SQUARE_OPENAPI_KEY }}

        steps:
             ions/setupactions/checkout@v4

                   - uses: actions/setup-node@v4
                           with:
                                     node-version: 24

                                           - run: node bot/index.mjs